import { chromium } from "playwright";
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1920, height: 1080 } });
const errs=[]; p.on("pageerror",e=>errs.push(String(e).slice(0,80)));
await p.goto("http://localhost:3001/sales-deck#45",{waitUntil:"networkidle"});
await p.waitForTimeout(1500); await p.screenshot({path:"/tmp/cv-car-1.png"});
await p.waitForTimeout(3000); await p.screenshot({path:"/tmp/cv-car-2.png"});
await p.waitForTimeout(3000); await p.screenshot({path:"/tmp/cv-car-3.png"});
await b.close();
console.log("ERR:"+(errs.length?errs[0]:"none"));
